/** @type {import('tailwindcss').Config} */
export default {
    darkMode: "class",

    content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
    theme: {
        extend: {
            height: {
                'fill': '-webkit-fill-available',
            },
            width: {
                inherit: "inherit",
                'fill': '-webkit-fill-available',
            },
            screens: {
                "3xl": "2000px",
            },
            colors: {
                primary: {
                    50: "#eff6ff",
                    100: "#dbeafe",
                    200: "#bfdbfe",
                    300: "#93c5fd",
                    400: "#60a5fa",
                    500: "#3b82f6",
                    600: "#2563eb",
                    700: "#1d4ed8",
                    800: "#1e40af",
                    900: "#1e3a8a",
                    950: "#172554",
                },
                "afrique-Vert-fonce": "#001C00",
                "afrique-Vert-clair": "#076423",
                "afrique-Vert-blanc": "#D3F1DC",
                "input-default-color": "#0B270B",

                // Palette AIPDA Europe
                "europe-blanc": "#CDCDEF",
                "europe-bleu-clair": "#3B3BF2",
                "europe-bleu-fonce": "#0505C3",
                "europe-dark-bleu": "#000827",

                // Palette AIPDA Monde
                "monde-noir": "#000827",
                "monde-gris": "#D4DEFF",
                "monde-bleu-fonce": "#000827",
                // Default color
                "default-color": "#0A1231",
            },
            keyframes: {
                bounceLeft: {
                    "0%, 100%": {transform: "translateX(0)"},
                    "50%": {transform: "translateX(-10px)"},
                },
                fade: {
                    "0%": {opacity: 0},
                    "50%": {opacity: 1},
                    "100%": {opacity: 0},
                },
            },
            animation: {
                bounceLeft: "bounceLeft 1s ease-in-out infinite",
                fade: "fade 2s ease-in-out infinite",
            },
        },
    },
    plugins: [require("tailwind-scrollbar")({nocompatible: true})],
    safelist: [
        "bg-afrique-Vert-fonce",
        "text-afrique-Vert-fonce",
        "text-afrique-Vert-blanc",
        "bg-afrique-Vert-blanc",
        "bg-afrique-Vert-clair",
        "bg-europe-bleu-fonce",
        "text-europe-blanc",
        "bg-europe-blanc",
        "bg-europe-bleu-clair",
        "bg-europe-dark-bleu",
        "bg-default-color",
        "text-default-color",
        "bg-input-default-color",
        "text-input-default-color",
        "border-europe-dark-bleu",
        "placeholder-europe-dark-bleu",
        "border-default-color",
        "placeholder-default-color",
        "border-input-default-color",
        "placeholder-input-default-color",
        "border-afrique-Vert-fonce",
        "hover:bg-afrique-Vert-fonce",
        "hover:text-afrique-Vert-blanc",
        "hover:bg-afrique-Vert-blanc",
        "hover:bg-afrique-Vert-clair",
        "hover:bg-europe-bleu-fonce",
        "hover:text-europe-blanc",
        "hover:bg-europe-blanc",
        "hover:bg-europe-bleu-clair",
        "hover:bg-europe-dark-bleu",
        "hover:bg-default-color",
        "hover:text-default-color",
        "hover:bg-input-default-color",
        "hover:text-input-default-color",
        "group-hover:bg-afrique-Vert-fonce",
        "group-hover:text-afrique-Vert-blanc",
        "group-hover:bg-afrique-Vert-blanc",
        "group-hover:bg-afrique-Vert-clair",
        "group-hover:bg-europe-bleu-fonce",
        "group-hover:text-europe-blanc",
        "group-hover:bg-europe-blanc",
        "group-hover:bg-europe-bleu-clair",
        "group-hover:bg-europe-dark-bleu",
        "group-hover:bg-default-color",
        "group-hover:text-default-color",
        "group-hover:bg-input-default-color",
        "group-hover:text-input-default-color",
        "fill-afrique-Vert-fonce",
        "fill-afrique-Vert-blanc",
        "fill-afrique-Vert-clair",
        "fill-europe-bleu-fonce",
        "fill-europe-blanc",
        "fill-europe-bleu-clair",
        "fill-europe-dark-bleu",
        "fill-default-color",
        "fill-input-default-color",
        "group-hover:fill-afrique-Vert-fonce",
        "group-hover:fill-afrique-Vert-blanc",
        "group-hover:fill-afrique-Vert-clair",
        "group-hover:fill-europe-bleu-fonce",
        "group-hover:fill-europe-blanc",
        "group-hover:fill-europe-bleu-clair",
        "group-hover:fill-europe-dark-bleu",
        "group-hover:fill-default-color",
        "group-hover:fill-input-default-color",
        "active:bg-afrique-Vert-fonce",
        "active:text-afrique-Vert-blanc",
        "active:bg-afrique-Vert-blanc",
        "active:bg-afrique-Vert-clair",
        "active:bg-europe-bleu-fonce",
        "active:text-europe-blanc",
        "active:bg-europe-blanc",
        "active:bg-europe-bleu-clair",
        "active:bg-europe-dark-bleu",
        "active:bg-default-color",
        "active:text-default-color",
        "active:bg-input-default-color",
        "active:text-input-default-color",
        "focus:bg-afrique-Vert-fonce",
        "focus:text-afrique-Vert-blanc",
        "focus:bg-afrique-Vert-blanc",
        "focus:bg-afrique-Vert-clair",
        "focus:bg-europe-bleu-fonce",
        "focus:text-europe-blanc",
        "focus:bg-europe-blanc",
        "focus:bg-europe-bleu-clair",
        "focus:bg-europe-dark-bleu",
        "focus:bg-default-color",
        "focus:text-default-color",
        "focus:bg-input-default-color",
        "focus:text-input-default-color",
        "text-europe-dark-bleu",
        "scrollbar-thumb-afrique-Vert-fonce",
        "scrollbar-thumb-afrique-Vert-blanc",
        "scrollbar-thumb-afrique-Vert-clair",
        "scrollbar-thumb-europe-bleu-fonce",
        "scrollbar-thumb-europe-blanc",
        "scrollbar-thumb-europe-bleu-clair",
        "scrollbar-thumb-europe-dark-bleu",
        "scrollbar-thumb-default-color",
        "scrollbar-thumb-input-default-color",
        "scrollbar-track-afrique-Vert-fonce",
        "scrollbar-track-afrique-Vert-blanc",
        "scrollbar-track-afrique-Vert-clair",
        "scrollbar-track-europe-bleu-fonce",
        "scrollbar-track-europe-blanc",
        "scrollbar-track-europe-bleu-clair",
        "scrollbar-track-europe-dark-bleu",
        "scrollbar-track-default-color",
        "scrollbar-track-input-default-color",
    ],
};
