// Tous les pays d'Afrique
export const paysAfrique = [
    "Algérie",
    "Angola",
    "Bénin",
    "Botswana",
    "Burkina Faso",
    "Burundi",
    "Cameroun",
    "Cap-Vert",
    "République centrafricaine",
    "Tchad",
    "Comores",
    "République du Congo",
    "République démocratique du Congo",
    "Djibouti",
    "Égypte",
    "Guinée équatoriale",
    "Érythrée",
    "Eswatini",
    "Éthiopie",
    "Gabon",
    "Gambie",
    "Ghana",
    "Guinée",
    "Guinée-Bissau",
    "Kenya",
    "Lesotho",
    "Libéria",
    "Libye",
    "Madagascar",
    "Malawi",
    "Mali",
    "Mauritanie",
    "Maurice",
    "Maroc",
    "Mozambique",
    "Namibie",
    "Niger",
    "Nigeria",
    "Rwanda",
    "Sao Tomé-et-Principe",
    "Sénégal",
    "Seychelles",
    "Sierra Leone",
    "Somalie",
    "Afrique du Sud",
    "Soudan",
    "Soudan du Sud",
    "Tanzanie",
    "Togo",
    "Tunisie",
    "Ouganda",
    "Zambie",
    "Zimbabwe",
    "Côte d'ivoire"
];

// Tous les pays d'Europe
export const paysEurope = [
    "Albanie",
    "Andorre",
    "Arménie",
    "Autriche",
    "Azerbaïdjan",
    "Biélorussie",
    "Belgique",
    "Bosnie-Herzégovine",
    "Bulgarie",
    "Croatie",
    "Chypre",
    "République tchèque",
    "Danemark",
    "Estonie",
    "Finlande",
    "France",
    "Géorgie",
    "Allemagne",
    "Grèce",
    "Hongrie",
    "Islande",
    "Irlande",
    "Italie",
    "Kazakhstan",
    "Kosovo",
    "Lettonie",
    "Liechtenstein",
    "Lituanie",
    "Luxembourg",
    "Malte",
    "Moldavie",
    "Monaco",
    "Monténégro",
    "Pays-Bas",
    "Macédoine du Nord",
    "Norvège",
    "Pologne",
    "Portugal",
    "Roumanie",
    "Russie",
    "Saint-Marin",
    "Serbie",
    "Slovaquie",
    "Slovénie",
    "Espagne",
    "Suède",
    "Suisse",
    "Turquie",
    "Ukraine",
    "Royaume-Uni",
    "Vatican",
];


export const paysAsie = [
    "Afghanistan",
    "Bahrain",
    "Bangladesh",
    "Bhutan",
    "Brunei",
    "Chine",
    "Corée du Sud",
    "Hong Kong",
    "Indonésie",
    "Indonésie",
    "Iran",
    "Israël",
    "Japon",
    "Jordanie",
    "Kazakhstan",
    "Kirghizistan",
    "Koweït",
    "Laos",
    "Liban",
    "Maldives",
    "Malaisie",
    "Myanmar",
    "Népal",
    "Nigéria",
    "Pakistan",
    "Philippines",
    "Qatar",
    "Corée du nord",
    "Singapour",
    "Sri Lanka",
    "Taïwan",
    "Thaïlande",
    "Timor oriental",
    "Viêt Nam",
    "Yemen",
];


export const paysAmerique = [
    "Canada",
    "États-Unis",
    "Mexique",
    "Argentine",
    "Barbade",
    "Belize",
    "Bermudes",
    "Bolivia",
    "Brésil",
    "Chili",
    "Colombie",
    "Costa Rica",
    "Cuba",
    "Dominique",
    "Guadeloupe",
    "Guatemala",
    "Guyane",
    "Haiti",
    "Honduras",
    "Jamaïque",
    "Martinique",
    "México",
    "Nicaragua",
    "Panama",
    "Paraguay",
    "Pérou",
    "Perou",
    "Saint-Barthélemy",
    "Saint-Martin",
    "Saint-Pierre-et-Miquelon",
    "Saint-Vincent-et-les-Grenadines",
    "Suriname",
    "Trinité-et-Tobago",
    "Uruguay",
    "Venezuela",
];












